export const GET_ADDRESS_REQUEST='GET_ADDRESS_REQUEST';
export const GET_ADDRESS_SUCCESS='GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAILURE='GET_ADDRESS_FAILURE';

export const UPDATE_ADDRESS_REQUEST='UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_SUCCESS='UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAILURE='UPDATE_ADDRESS_FAILURE';

export const CREATE_ADDRESS_REQUEST='CREATE_ADDRESS_REQUEST';
export const CREATE_ADDRESS_SUCCESS='CREATE_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_FAILURE='CREATE_ADDRESS_FAILURE';

export const REMOVE_ADDRESS_REQUEST='REMOVE_ADDRESS_REQUEST';
export const REMOVE_ADDRESS_SUCCESS='REMOVE_ADDRESS_SUCCESS';
export const REMOVE_ADDRESS_FAILURE='REMOVE_ADDRESS_FAILURE';